[build]
  functions = "netlify-functions"
  publish = "."
  command = "echo 'No build step required'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18" 